### ISSUE TITLE
v0.1 Spelling Errors And Proofreading

### ISSUE THREAD

**Issue by Cryptopone** [Swizec/nightowls#1]
Reading through v0.1 of your book and noticed a couple of spelling errors and a difficult to follow sentence.

Spelling errors in the flow section (pg 9):

Discovered in the 1950’s [fact check] by [guy who did] when he was observing artists, especially
painters, who **woudl** _would_ get so lost **int heir** _in their_ work they could forget to eat, drink and lose track of time to the point of forgetting what day it is.

Difficulty following sentence in About Flow - Cost of Interruption (pg 17)

First, a programmer needs to make sure they are working off the latest version of the project. **Then
they must whatever issue tracking system they’re using.** Having a clear goal is after all paramount
to achieving flow and getting anything done.

Spelling in Primer on Sleep Science (pg 20)

This is because the light coming off our screens is very white, aimed right at our eyes and usually
insanely bright because monitors are set to stupid brightness levels by default and most people forget
to **changesdfsdf** those.

**Comment by Kopac** [comment]
Also:
A primer on sleep science, section Bright screens (pg 20)

One of the biggest factors in human sleep-wake cycle is natural **lgiht** _light_.

I also think the final sentence should have a comma before _huh_.
Because we aren’t sleepy, we might as well **work huh** _work, huh_?

**Comment by soulseekah** [comment]
Will try to submit patches for the other ones mentioned here once I get to them while actually reading.

**Comment by Swizec** [comment]
Thanks for reporting the typos, I also seemed to have missed the [fact check] notes when reviewing before publishing. Oops :)

@Kopac The sleep stuff chapter is very rough and more a random collection of thoughts right now. It will likely get completely rewritten.
