### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by koenekelschot** [Swizec/nightowls#7]
Reading through v0.3 of your book and noticed a couple of small typos.

The first typo can be found in sleep-science.md:

> Eventually your sleep cycle shifts into a different timezone because you keep goign to bed later and later...

"goign" should be "going"

And the second topy can be found in howforfriends.md (in the section Batch processing):

> When a programmer has reached a natural stopping point int heir work they are naturally inclined to take a little break.

"int heir" should be "in their"

**Comment by Swizec** [comment]
Thanks for noticing and letting me know! Sorry it took me so long to fix :)
